name: Build test apk after sync

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [Sync Fork]
    types: [completed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Generate Release APK
        run: ./gradlew assembleRelease      
      
      # - name: Generate Debug APK
      #   run: ./gradlew assembleDebug
      
      - name: Sign Release APK
        uses: ilharp/sign-android-release@v1
        # ID used to access action output
        id: sign_app_release
        with:
          releaseDir: app/phone/build/outputs/apk/libre/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 35.0.0
          
      # - name: Sign Debug APK
      #   uses: ilharp/sign-android-release@v1
      #   # ID used to access action output
      #   id: sign_app_debug
      #   with:
      #     releaseDir: app/phone/build/outputs/apk/libre/debug
      #     signingKey: ${{ secrets.SIGNING_KEY }}
      #     keyAlias: ${{ secrets.ALIAS }}
      #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      #     keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Set tag
        id: tag
        run: echo "tag=$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: List release files
        working-directory: app/phone/build/outputs/apk/libre/release/
        run: ls -l
        
      - name: Rename Release APK
        working-directory: app/phone/build/outputs/apk/libre/release/
        run: mv phone-libre-arm64-v8a-release-unsigned-signed.apk testing-release-libre-arm64-v8a-${{ steps.tag.outputs.tag }}.apk

      # - name: Rename Debug APK
      #   working-directory: app/phone/build/outputs/apk/libre/debug/
      #   run: mv phone-libre-arm64-v8a-debug-signed.apk testing-debug-libre-arm64-v8a-${{ steps.tag.outputs.tag }}.apk

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: findroid-apk
          path: |
            app/phone/build/outputs/apk/libre/release/testing-release-libre-arm64-v8a-${{ steps.tag.outputs.tag }}.apk   
          # app/phone/build/outputs/apk/libre/debug/testing-debug-libre-arm64-v8a-${{ steps.tag.outputs.tag }}.apk
       
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.tag.outputs.tag }}
          prerelease: false
          title: "Testing Build"
          files: |
            app/phone/build/outputs/apk/libre/release/testing-release-libre-arm64-v8a-${{ steps.tag.outputs.tag }}.apk
          # app/phone/build/outputs/apk/libre/debug/testing-debug-libre-arm64-v8a-${{ steps.tag.outputs.tag }}.apk